export enum DIFFICULT_LEVELS {
  HARD = 'HARD',
  MEDIUM = 'MEDIUM',
  EASY = 'EASY',
}

export enum MEAL_CATEGORIES {
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  BRUNCH = 'BRUNCH',
  DINNER = 'DINNER',
  BURGER = 'BURGER',
  SALAD = 'SALAD',
  SOUP = 'SOUP',
  APPETIZER = 'APPETIZER',
  DESSERT = 'DESSERT',
  HOTPOT = 'HOTPOT',
  NORTH_VN = 'NORTH_VN',
  CENTRAL_VN = 'CENTRAL_VN',
  SOUTH_VN = 'SOUTH_VN',
  SWEET_SOUP = 'SWEET_SOUP',
  VITAMIN = 'VITAMIN',
}
