export const Permissions = {
  CREATE_ROLE: 'CREATE_ROLE',
  FIND_ALL_ROLE: 'FIND_ALL_ROLE',
  FIND_ONE_ROLE: 'FIND_ONE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  REMOVE_ROLE: 'REMOVE_ROLE',

  CREATE_USER: 'CREATE_USER',
  FIND_ALL_USER: 'FIND_ALL_USER',
  FIND_ONE_USER: 'FIND_ONE_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
  DELETE_USER_DATA: 'DELETE_USER_DATA',

  CREATE_DISH: 'CREATE_DISH',
  FIND_ALL_DISH: 'FIND_ALL_DISH',
  FIND_ONE_DISH: 'FIND_ONE_DISH',
  UPDATE_DISH: 'UPDATE_DISH',
  REMOVE_DISH: 'REMOVE_DISH',

  CREATE_INGREDIENT: 'CREATE_INGREDIENT',
  FIND_ALL_INGREDIENT: 'FIND_ALL_INGREDIENT',
  FIND_ONE_INGREDIENT: 'FIND_ONE_INGREDIENT',
  UPDATE_INGREDIENT: 'UPDATE_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',

  ADMIN_DASHBOARD: 'ADMIN_DASHBOARD',

  CREATE_CONTACT: 'CREATE_CONTACT',
  FIND_ALL_CONTACT: 'FIND_ALL_CONTACT',
  FIND_ONE_CONTACT: 'FIND_ONE_CONTACT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT',

  CREATE_DISH_VOTE: 'CREATE_DISH_VOTE',
  FIND_ALL_DISH_VOTE: 'FIND_ALL_DISH_VOTE',
  FIND_ONE_DISH_VOTE: 'FIND_ONE_DISH_VOTE',
  UPDATE_DISH_VOTE: 'UPDATE_DISH_VOTE',
  REMOVE_DISH_VOTE: 'REMOVE_DISH_VOTE',

  FIND_USER_LOGIN_TRACK: 'FIND_USER_LOGIN_TRACK',
  FIND_ALL_USER_LOGIN_TRACK: 'FIND_ALL_USER_LOGIN_TRACK',

  CREATE_WEBSITE_VISIT: 'CREATE_WEBSITE_VISIT',
  FIND_ALL_WEBSITE_VISIT: 'FIND_ALL_WEBSITE_VISIT',
  FIND_ONE_WEBSITE_VISIT: 'FIND_ONE_WEBSITE_VISIT',
  UPDATE_WEBSITE_VISIT: 'UPDATE_WEBSITE_VISIT',
  REMOVE_WEBSITE_VISIT: 'REMOVE_WEBSITE_VISIT',
};
